spring:
    datasource:
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
#    datasource:
#        url: jdbc:h2:file:./src/main/resources/db/h2db
#        username: sa
#        password: password
#        driverClassName: org.h2.Driver
    jpa:
#        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
#        hibernate:
#            ddl-auto: update
#    h2:
#        console:
#            enabled: true
#    sql:
#        init:
#            mode: embedded